version: '2'

services:
  elasticsearch:
    image: 'ygqygq2/elasticsearch:5.6.16-debian-9'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
